package greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import greendao.NeoUser;
import greendao.NeoChatHistory;
import greendao.NeoContractLately;

import greendao.NeoUserDao;
import greendao.NeoChatHistoryDao;
import greendao.NeoContractLatelyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig neoUserDaoConfig;
    private final DaoConfig neoChatHistoryDaoConfig;
    private final DaoConfig neoContractLatelyDaoConfig;

    private final NeoUserDao neoUserDao;
    private final NeoChatHistoryDao neoChatHistoryDao;
    private final NeoContractLatelyDao neoContractLatelyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        neoUserDaoConfig = daoConfigMap.get(NeoUserDao.class).clone();
        neoUserDaoConfig.initIdentityScope(type);

        neoChatHistoryDaoConfig = daoConfigMap.get(NeoChatHistoryDao.class).clone();
        neoChatHistoryDaoConfig.initIdentityScope(type);

        neoContractLatelyDaoConfig = daoConfigMap.get(NeoContractLatelyDao.class).clone();
        neoContractLatelyDaoConfig.initIdentityScope(type);

        neoUserDao = new NeoUserDao(neoUserDaoConfig, this);
        neoChatHistoryDao = new NeoChatHistoryDao(neoChatHistoryDaoConfig, this);
        neoContractLatelyDao = new NeoContractLatelyDao(neoContractLatelyDaoConfig, this);

        registerDao(NeoUser.class, neoUserDao);
        registerDao(NeoChatHistory.class, neoChatHistoryDao);
        registerDao(NeoContractLately.class, neoContractLatelyDao);
    }
    
    public void clear() {
        neoUserDaoConfig.getIdentityScope().clear();
        neoChatHistoryDaoConfig.getIdentityScope().clear();
        neoContractLatelyDaoConfig.getIdentityScope().clear();
    }

    public NeoUserDao getNeoUserDao() {
        return neoUserDao;
    }

    public NeoChatHistoryDao getNeoChatHistoryDao() {
        return neoChatHistoryDao;
    }

    public NeoContractLatelyDao getNeoContractLatelyDao() {
        return neoContractLatelyDao;
    }

}
