package greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NEO_CONTRACT_LATELY".
 */
@Entity
public class NeoContractLately {

    @Id
    @NotNull
    private String friendJID;

    @NotNull
    private String friendName;

    @NotNull
    private String myJID;
    private Integer num;
    private long time;

    @NotNull
    private String body;

    @Generated
    public NeoContractLately() {
    }

    public NeoContractLately(String friendJID) {
        this.friendJID = friendJID;
    }

    @Generated
    public NeoContractLately(String friendJID, String friendName, String myJID, Integer num, long time, String body) {
        this.friendJID = friendJID;
        this.friendName = friendName;
        this.myJID = myJID;
        this.num = num;
        this.time = time;
        this.body = body;
    }

    @NotNull
    public String getFriendJID() {
        return friendJID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFriendJID(@NotNull String friendJID) {
        this.friendJID = friendJID;
    }

    @NotNull
    public String getFriendName() {
        return friendName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFriendName(@NotNull String friendName) {
        this.friendName = friendName;
    }

    @NotNull
    public String getMyJID() {
        return myJID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMyJID(@NotNull String myJID) {
        this.myJID = myJID;
    }

    public Integer getNum() {
        return num;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    @NotNull
    public String getBody() {
        return body;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBody(@NotNull String body) {
        this.body = body;
    }

}
