package greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NEO_CHAT_HISTORY".
 */
@Entity
public class NeoChatHistory {

    @Id(autoincrement = true)
    private Long id;
    private String myJID;
    private String friendJID;
    private Long time;
    private Integer sendState;
    private String body;
    private Boolean isSend;

    @Generated
    public NeoChatHistory() {
    }

    public NeoChatHistory(Long id) {
        this.id = id;
    }

    @Generated
    public NeoChatHistory(Long id, String myJID, String friendJID, Long time, Integer sendState, String body, Boolean isSend) {
        this.id = id;
        this.myJID = myJID;
        this.friendJID = friendJID;
        this.time = time;
        this.sendState = sendState;
        this.body = body;
        this.isSend = isSend;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMyJID() {
        return myJID;
    }

    public void setMyJID(String myJID) {
        this.myJID = myJID;
    }

    public String getFriendJID() {
        return friendJID;
    }

    public void setFriendJID(String friendJID) {
        this.friendJID = friendJID;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Integer getSendState() {
        return sendState;
    }

    public void setSendState(Integer sendState) {
        this.sendState = sendState;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public Boolean getIsSend() {
        return isSend;
    }

    public void setIsSend(Boolean isSend) {
        this.isSend = isSend;
    }

}
