package greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NEO_USER".
*/
public class NeoUserDao extends AbstractDao<NeoUser, String> {

    public static final String TABLENAME = "NEO_USER";

    /**
     * Properties of entity NeoUser.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Name = new Property(0, String.class, "name", true, "NAME");
        public final static Property Password = new Property(1, String.class, "password", false, "PASSWORD");
    };


    public NeoUserDao(DaoConfig config) {
        super(config);
    }
    
    public NeoUserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NEO_USER\" (" + //
                "\"NAME\" TEXT PRIMARY KEY NOT NULL ," + // 0: name
                "\"PASSWORD\" TEXT NOT NULL );"); // 1: password
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NEO_USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NeoUser entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getName());
        stmt.bindString(2, entity.getPassword());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NeoUser entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getName());
        stmt.bindString(2, entity.getPassword());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    @Override
    public NeoUser readEntity(Cursor cursor, int offset) {
        NeoUser entity = new NeoUser( //
            cursor.getString(offset + 0), // name
            cursor.getString(offset + 1) // password
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NeoUser entity, int offset) {
        entity.setName(cursor.getString(offset + 0));
        entity.setPassword(cursor.getString(offset + 1));
     }
    
    @Override
    protected final String updateKeyAfterInsert(NeoUser entity, long rowId) {
        return entity.getName();
    }
    
    @Override
    public String getKey(NeoUser entity) {
        if(entity != null) {
            return entity.getName();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
