package greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NEO_USER".
 */
@Entity
public class NeoUser {

    @Id
    @NotNull
    private String name;

    @NotNull
    private String password;

    @Generated
    public NeoUser() {
    }

    public NeoUser(String name) {
        this.name = name;
    }

    @Generated
    public NeoUser(String name, String password) {
        this.name = name;
        this.password = password;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    @NotNull
    public String getPassword() {
        return password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassword(@NotNull String password) {
        this.password = password;
    }

}
